web/router.ex
defmodule DidICommit.Router do
  use DidICommit.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DidICommit do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/auth", DidICommit do
    pipe_through :browser

    get "/", AuthController, :index
    get "/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end

  # Other scopes may use custom stacks.
  # scope "/api", DidICommit do
  #   pipe_through :api
  # end
end

lib/did_i_commit/endpoint.ex
defmodule DidICommit.Endpoint do
  use Phoenix.Endpoint, otp_app: :did_i_commit

  socket "/socket", DidICommit.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :did_i_commit, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_did_i_commit_key",
    signing_salt: "xqEeD8F0"

  plug DidICommit.Router
end

lib/did_i_commit/repo.ex
defmodule DidICommit.Repo do
  use Ecto.Repo, otp_app: :did_i_commit
end

web/models/auth.ex
defmodule DidICommit.Auth do
  use DidICommit.Web, :model

  schema "auth" do

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [])
    |> validate_required([])
  end
end

web/controllers/auth_controller.ex
defmodule DidICommit.AuthController do
  use DidICommit.Web, :controller

  alias DidICommit.Auth

  def index(conn, _params) do
    redirect conn, external: GitHub.authorize_url!
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> configure_session(drop: true)
    |> redirect(to: "/")
  end

  def callback(conn, %{"code" => code}) do
    client = GitHub.get_token!(code: code)
    user = get_user!(client)
    
    conn
    |> put_session(:current_user, user)
    |> put_session(:client, client)
    |> redirect(to: "/")
  end
  
  defp get_user!(client) do
    {:ok, %{body: user}} = OAuth2.Client.get(client, "/user")
    %{name: user["name"], avatar: user["avatar_url"], username: user["login"]}
  end
end

web/controllers/page_controller.ex
defmodule DidICommit.PageController do
  use DidICommit.Web, :controller

  def index(conn, _params) do
    result = if conn.assigns.current_user do
      today = Timex.now
      #TODO need to get timezone info from client
      timezone = Timex.Timezone.get("America/Chicago", today)
      today = Timex.Timezone.convert(today, timezone)
      today = Timex.beginning_of_day(today)
      tomorrow = Timex.end_of_day(today)

      # IO.inspect today
      # IO.inspect tomorrow

      {:ok, %{body: events}} = OAuth2.Client.get(get_session(conn, :client), "/users/" <> conn.assigns.current_user.username <> "/events")
      events
      |> Enum.filter(fn(%{"type" => type, "created_at" => created_at}) ->	
	created_at = Timex.Timezone.convert(Timex.parse!(created_at, "{ISO:Extended}"), timezone)
	type == "PushEvent" && Timex.between?(created_at, today, tomorrow)
      end)
    end
    
    render conn, "index.html", commit: !Enum.empty?(result || [])
  end
end

web/views/auth_view.ex
defmodule DidICommit.AuthView do
  use DidICommit.Web, :view

  def render("index.json", %{auth: auth}) do
    %{data: render_many(auth, DidICommit.AuthView, "auth.json")}
  end

  def render("show.json", %{auth: auth}) do
    %{data: render_one(auth, DidICommit.AuthView, "auth.json")}
  end

  def render("auth.json", %{auth: auth}) do
    %{id: auth.id}
  end
end

web/views/changeset_view.ex
defmodule DidICommit.ChangesetView do
  use DidICommit.Web, :view

  @doc """
  Traverses and translates changeset errors.

  See `Ecto.Changeset.traverse_errors/2` and
  `DidICommit.ErrorHelpers.translate_error/1` for more details.
  """
  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  def render("error.json", %{changeset: changeset}) do
    # When encoded, the changeset returns its errors
    # as a JSON object. So we just pass it forward.
    %{errors: translate_errors(changeset)}
  end
end

web/views/error_view.ex
defmodule DidICommit.ErrorView do
  use DidICommit.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule DidICommit.LayoutView do
  use DidICommit.Web, :view
end

web/views/page_view.ex
defmodule DidICommit.PageView do
  use DidICommit.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Did I Commit?</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    
  </head>

  <body>
    <nav class="navbar navbar-static-top navbar-top navbar-inverse">
      <div class="container-fluid">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
	  <a href="#" class="navbar-brand navbar-left">Did I commit today?</a>
	</div>
	<div id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
	  
	    <%= if @current_user do %>
	      <img class="avatar img-circle pull-left hidden-xs" src="<%= @current_user.avatar%>" />
	      <p class="navbar-text pull-left">Logged in as <%= @current_user.name %></p>
	      <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-primary navbar-btn pull-right" %>
	    <% else %>
	      <a href="<%= auth_path @conn, :index %>">
		<button type="button" class="btn btn-primary navbar-btn pull-right">Login</button>
	      </a>
	    <% end %>
	 
	</div>
    </nav>
    
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<main>
  <span class="message">
    <%= if @current_user do %>
      <%= if @commit do %>
        Yep!
      <% else %>
        Nope.
      <% end %>
    <% else %>
      ¯\_(ツ)_/¯
    <% end %>
  </span>
</main>